USE [master]
GO
/****** Object:  Database [Scadenzario]    Script Date: 16/03/2021 05:38:04 ******/
CREATE DATABASE [Scadenzario]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Scadenzario', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Scadenzario.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Scadenzario_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Scadenzario_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Scadenzario] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Scadenzario].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Scadenzario] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Scadenzario] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Scadenzario] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Scadenzario] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Scadenzario] SET ARITHABORT OFF 
GO
ALTER DATABASE [Scadenzario] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Scadenzario] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Scadenzario] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Scadenzario] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Scadenzario] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Scadenzario] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Scadenzario] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Scadenzario] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Scadenzario] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Scadenzario] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Scadenzario] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Scadenzario] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Scadenzario] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Scadenzario] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Scadenzario] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Scadenzario] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Scadenzario] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Scadenzario] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Scadenzario] SET  MULTI_USER 
GO
ALTER DATABASE [Scadenzario] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Scadenzario] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Scadenzario] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Scadenzario] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Scadenzario] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Scadenzario] SET QUERY_STORE = OFF
GO
USE [Scadenzario]
GO
/****** Object:  Table [dbo].[Beneficiari]    Script Date: 16/03/2021 05:38:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Beneficiari](
	[IDBeneficiario] [int] IDENTITY(1,1) NOT NULL,
	[Beneficiario] [nvarchar](150) NOT NULL,
	[Descrizione] [nvarchar](max) NOT NULL,
	[Email] [nvarchar](50) NULL,
	[Telefono] [nvarchar](20) NULL,
	[SitoWeb] [nvarchar](80) NULL,
 CONSTRAINT [PK_Beneficiari] PRIMARY KEY CLUSTERED 
(
	[IDBeneficiario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Ricevute]    Script Date: 16/03/2021 05:38:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ricevute](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IDScadenza] [int] NOT NULL,
	[FileName] [nvarchar](50) NOT NULL,
	[FileType] [nvarchar](50) NOT NULL,
	[FileContent] [image] NOT NULL,
	[Beneficiario] [nvarchar](150) NOT NULL,
 CONSTRAINT [PK_Ricevute] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Scadenze]    Script Date: 16/03/2021 05:38:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Scadenze](
	[IDScadenza] [int] IDENTITY(1,1) NOT NULL,
	[IDUser] [int] NOT NULL,
	[IDBeneficiario] [int] NOT NULL,
	[Beneficiario] [nvarchar](150) NOT NULL,
	[DataScadenza] [datetime] NOT NULL,
	[Importo] [decimal](18, 2) NOT NULL,
	[Sollecito] [bit] NOT NULL,
	[GiorniRitardo] [smallint] NULL,
	[DataPagamento] [datetime] NULL,
 CONSTRAINT [PK_Scadenze] PRIMARY KEY CLUSTERED 
(
	[IDScadenza] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Scadenze] ADD  CONSTRAINT [DF_Scadenze_Sollecito]  DEFAULT ((0)) FOR [Sollecito]
GO
ALTER TABLE [dbo].[Ricevute]  WITH CHECK ADD  CONSTRAINT [FK_Scadenze_Ricevute] FOREIGN KEY([IDScadenza])
REFERENCES [dbo].[Scadenze] ([IDScadenza])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Ricevute] CHECK CONSTRAINT [FK_Scadenze_Ricevute]
GO
ALTER TABLE [dbo].[Scadenze]  WITH CHECK ADD  CONSTRAINT [FK_Scadenze_Beneficiario] FOREIGN KEY([IDBeneficiario])
REFERENCES [dbo].[Beneficiari] ([IDBeneficiario])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Scadenze] CHECK CONSTRAINT [FK_Scadenze_Beneficiario]
GO
USE [master]
GO
ALTER DATABASE [Scadenzario] SET  READ_WRITE 
GO
